<h2 style="color:#9D2449; font-family:'Montserrat', sans-serif; font-size:30px; font-weight:700; margin-top:25px; margin-bottom:12px;">
Análisis Exploratorio de Datos para el Desarrollo de una Aplicación de Turismo en Hidalgo
</h2>

Se recibió la base de datos resultante de un instrumento de levantamiento de información aplicado en tres destinos turísticos del Estado de Hidalgo, diseñado e implementado por el área correspondiente. El instrumento fue aplicado a dos poblaciones objetivo: **807 turistas** y **aproximadamente 100 Prestadores de Servicios Turísticos (PST)**.

El presente notebook documenta el proceso de limpieza, estandarización y análisis exploratorio de ambas bases de datos. El análisis busca responder preguntas clave sobre el perfil de cada población:

- **Turistas:** ¿De dónde provienen? ¿Cómo y cuándo viajan? ¿Qué buscan en un destino? ¿Qué esperan de una aplicación de turismo desarrollada por el gobierno del estado?
- **PST:** ¿Cuál es su perfil y tipo de servicio? ¿Qué dificultades enfrentan? ¿Qué canales de promoción utilizan? ¿Qué esperan de una plataforma digital?

Los hallazgos e insights derivados del análisis fueron entregados al equipo de desarrollo como insumo para la definición de los MVP de la aplicación. Los datos procesados se exportan como archivos `.csv` limpios para su visualización en **Looker Studio**.

In [291]:
import pandas as pd
import numpy as np
import kagglehub

<h2 style="color:#9D2449; font-family:'Montserrat', sans-serif; font-size:28px; font-weight:700; margin-top:25px; margin-bottom:12px;">
Turistas
</h2>

<h4 style="color:#0F3D36; font-family:'Montserrat', sans-serif; font-size:20px; font-weight:600; margin-top:15px; margin-bottom:8px;">
Carga de Datos
</h4>

In [292]:
path = "https://raw.githubusercontent.com/gonza98kg/Turistas/main/TURISTAS_data.csv"

df = pd.read_csv(path)

df.head()

,Id,1. ¿De dónde nos visitas?,1.1 ¿De qué municipio del estado de Hidalgo perteneces?,2. ¿En qué rango de edad te encuentras?,3. ¿Con qué género te identificas?\n,4. ¿Con qué frecuencia realizas viajes dentro de México?\n,5. ¿Cuántas veces ha visitado alguno de los destinos turísticos de Hidalgo en los últimos 24 meses?\n,6. ¿Qué tanto te motiva principalmente a viajar los siguientes aspectos?\n,6. ¿Qué tanto te motiva principalmente a viajar los siguientes aspectos?\n (Otro),7. Los medios donde buscas inspiración para elegir destinos en Hidalgo.,...,12. ¿Qué tipo de información consideras más importante?,12. ¿Qué tipo de información consideras más importante? (Otro),13. ¿Con qué frecuencia has enfrentado los siguientes problemas al viajar?,13. ¿Con qué frecuencia has enfrentado los siguientes problemas al viajar? (Otro),"14. En una escala del 1 al 5, donde 1 es nada probable y 5 muy probable. ¿Qué tan probable es que uses una app oficial del estado de Hidalgo para planear y vivir tus viajes?\n",15. ¿Qué funciones consideras indispensables en una app de viajes?,15. ¿Qué funciones consideras indispensables en una app de viajes? (Otro),16. ¿Qué haría que dejaras de usar una app turística? (Selecciona 3 opciones),"17. En una frase, ¿qué esperas de una app turística ideal para viajar en Hidalgo?\n","17. En una frase, ¿qué esperas de una app turística ideal para viajar en Hidalgo?\n (Otro)"
0,1,Campeche,NaN,50–59 años,Hombre,Esporádicamente,1 vez,Gastronomía,NaN,Recomendaciones de amigos / familia,...,Mapas y rutas,NaN,Falta de información en el momento exacto,NaN,5,Eventos y experiencias locales,NaN,Exceso de publicidad,Información que me ayude a decidir a donde ir,NaN
1,2,Ciudad de México,NaN,18–29 años,Hombre,Varias veces al año,2 veces,Naturaleza,NaN,Blogs o influencers,...,Eventos o actividades del día,NaN,Información desactualizada,NaN,5,Información verificada,NaN,Información falsa o incompleta,Información concreta,NaN
2,3,Estado de México,NaN,18–29 años,Mujer,Varias veces al año,3 veces,Gastronomía,NaN,Recomendaciones de amigos / familia,...,Eventos o actividades del día,NaN,Falta de información en el momento exacto,NaN,5,Comercios y servicios cercanos,NaN,"Información falsa o incompleta, Exceso de publ...",Auténtica,NaN
3,4,Estado de México,NaN,30–39 años,Mujer,Esporádicamente,4 veces o más,Aventura,NaN,Redes sociales,...,Otro: Todo,NaN,Falta de información en el momento exacto,NaN,5,Otro: Todas,NaN,"Información falsa o incompleta, Exceso de publ...",Todos los sitios turísticos y rutas y que no s...,NaN
4,5,Ciudad de México,NaN,18–29 años,Mujer,Varias veces al año,2 veces,Naturaleza,NaN,Redes sociales,...,Mapas y rutas,NaN,Falta de información en el momento exacto,NaN,5,Eventos y experiencias locales,NaN,Información falsa o incompleta,"Que sea funcional, rápida y actualizada",NaN

In [293]:
df.shape

(807, 27)

<h4 style="color:#0F3D36; font-family:'Montserrat', sans-serif; font-size:20px; font-weight:600; margin-top:15px; margin-bottom:8px;">
Diccionario
</h4>

| **Columna**                | **Tipo de dato**   | **Descripción**|
|----------------------------|--------------------|----------------|
| Id                     | Entero (`int`)     | Identificador único del turista |
| 1. ¿De dónde nos visitas? | Cadena (`string`)  | Estado de residencia del turista |
| 1.1 ¿De qué municipio del estado de Hidalgo perteneces? | Cadena (`string`)     | Municipio de residencia en Hidalgo del turista |
| 2. ¿En qué rango de edad te encuentras? | Cadena (`string`)     | Rango de edad del turista |
| 3. ¿Con qué género te identificas?\n | Cadena (`string`)     | Género del turista |
| 4. ¿Con qué frecuencia realizas viajes dentro de México?\n | Cadena (`string`)     | Frecuencia de viaje del turista dentro del país |
| 5. ¿Cuántas veces ha visitado alguno de los destinos turísticos de Hidalgo en los últimos 24 meses?\n | Cadena (`string`)     | Frecuencia de viaje del turista dentro de Hidalgo |
| 6. ¿Qué tanto te motiva principalmente a viajar los siguientes aspectos?\n | Cadena (`string`)     | Principal motivador de viaje del turista |
| 7. Los medios donde buscas inspiración para elegir destinos en Hidalgo. | Cadena(`string`)     | Medios principales donde se escoge destino turístico en Hidalgo |
| 8. En cuanto a la confianza y uso de las tecnologías indica tu nivel en que estas de acuerdo con las siguientes frases: | Cadena (`string`)     | Percepción del turista al uso de herramientas digitales |
| 9. ¿Qué factor influye más en tu decisión de seguir una recomendación turística? | Cadena (`string`)     | Factores principales para elegir recomendaciones turísticas |
| 10. En una escala del 1 al 5 donde 1 es Nada valioso y 5 es Muy valioso ¿Cómo sería para ti que una app turística te recomiende comercios y experiencias locales auténticas? | Entero (`int`)     | Valoración de que una app recomiende experiencias turísticas |
| 11. De una escala del 1 al 5 donde 1 es Totalmente en desacuerdo y 5 es Totalmente de acuerdo. Indica que tanto estás de acuerdo con la siguiente frase: "Me sentiría más confiado/a usando una app turística si sé que las recomendaciones están validadas por personas locales o por una institución oficial.” | Entero (`int`)     | Valoración sobre la influencia de la validación local o institucional en la confianza para usar una app turística |
| 12. ¿Qué tipo de información consideras más importante? | Cadena (`string`)     | Información considerada relevante para la elección del destino turístico |
| 13. ¿Con qué frecuencia has enfrentado los siguientes problemas al viajar? | Cadena (`string`)     | Problemas más comunes al momento de viajar |
| 14. En una escala del 1 al 5, donde 1 es nada probable y 5 muy probable. ¿Qué tan probable es que uses una app oficial del estado de Hidalgo para planear y vivir tus viajes? | Entero (`int`)     | Valoración sobre la probabilidad de usar una app oficial para turistas |
| 15. ¿Qué funciones consideras indispensables en una app de viajes? | Cadena (`string`)     | Funciones consideradas importantes que muestre la app oficial para turistas |
| 16. ¿Qué haría que dejaras de usar una app turística? (Selecciona 3 opciones) | Cadena (`string`)     | Factores que harían que el turista dejara de usar la app de turismo |
| 17. En una frase, ¿qué esperas de una app turística ideal para viajar en Hidalgo? | Cadena (`string`)     | Expectativas del turista sobre la app de turismo |

In [294]:
porcentajes = (df.isnull().sum()/len(df))*100

tabla_info = pd.DataFrame({

    "Data Type": df.dtypes,
    "No Nulos": df.notnull().sum(),
    "Valores Nulos" : df.isnull().sum(),
    "Porcentaje Nulos (%)": porcentajes.round(2),
})

tabla_info

,Data Type,No Nulos,Valores Nulos,Porcentaje Nulos (%)
Id,int64,807,0,0.00
1. ¿De dónde nos visitas?,object,806,1,0.12
1.1 ¿De qué municipio del estado de Hidalgo perteneces?,object,249,558,69.14
2. ¿En qué rango de edad te encuentras?,object,804,3,0.37
3. ¿Con qué género te identificas?\n,object,800,7,0.87
4. ¿Con qué frecuencia realizas viajes dentro de México?\n,object,798,9,1.12
5. ¿Cuántas veces ha visitado alguno de los destinos turísticos de Hidalgo en los últimos 24 meses?\n,object,803,4,0.50
6. ¿Qué tanto te motiva principalmente a viajar los siguientes aspectos?\n,object,806,1,0.12
6. ¿Qué tanto te motiva principalmente a viajar los siguientes aspectos?\n (Otro),float64,0,807,100.00
7. Los medios donde buscas inspiración para elegir destinos en Hidalgo.,object,800,7,0.87
7. Los medios donde buscas inspiración para elegir destinos en Hidalgo. (Otro),float64,0,807,100.00
8. En cuanto a la confianza y uso de las tecnologías indica tu nivel en que estas de acuerdo con las siguientes frases:,object,795,12,1.49
8. En cuanto a la confianza y uso de las tecnologías indica tu nivel en que estas de acuerdo con las siguientes frases: (Otro),float64,0,807,100.00
9. ¿Qué factor influye más en tu decisión de seguir una recomendación turística?,object,805,2,0.25
9. ¿Qué factor influye más en tu decisión de seguir una recomendación turística? (Otro),float64,0,807,100.00
10. En una escala del 1 al 5 donde 1 es Nada valioso y 5 es Muy valioso ¿Cómo sería para ti que una app turística te recomiende comercios y experiencias locales auténticas?\n,float64,802,5,0.62
"11. De una escala del 1 al 5 donde 1 es Totalmente en desacuerdo y 5 es Totalmente de acuerdo. Indica que tanto estás de acuerdo con la siguiente frase: ""Me sentiría más confiado/a usando una app turística si sé que las recomendaciones están validadas por personas locales o por una institución oficial.”\n",float64,801,6,0.74
12. ¿Qué tipo de información consideras más importante?,object,804,3,0.37
12. ¿Qué tipo de información consideras más importante? (Otro),float64,0,807,100.00
13. ¿Con qué frecuencia has enfrentado los siguientes problemas al viajar?,object,804,3,0.37
13. ¿Con qué frecuencia has enfrentado los siguientes problemas al viajar? (Otro),float64,0,807,100.00
"14. En una escala del 1 al 5, donde 1 es nada probable y 5 muy probable. ¿Qué tan probable es que uses una app oficial del estado de Hidalgo para planear y vivir tus viajes?\n",object,799,8,0.99
15. ¿Qué funciones consideras indispensables en una app de viajes?,object,803,4,0.50
15. ¿Qué funciones consideras indispensables en una app de viajes? (Otro),float64,0,807,100.00
16. ¿Qué haría que dejaras de usar una app turística? (Selecciona 3 opciones),object,805,2,0.25
"17. En una frase, ¿qué esperas de una app turística ideal para viajar en Hidalgo?\n",object,718,89,11.03
"17. En una frase, ¿qué esperas de una app turística ideal para viajar en Hidalgo?\n (Otro)",float64,0,807,100.00

<h4 style="color:#0F3D36; font-family:'Montserrat', sans-serif; font-size:20px; font-weight:600; margin-top:15px; margin-bottom:8px;">
Limpieza de la base de datos
</h4>

Se observa que algunas columnas presentan valores numéricos repetidos con todos sus registros nulos, por lo que resulta conveniente eliminarlas. La tabla de información se actualiza tras la limpieza.

In [295]:
df = df.drop(columns=["Id","6. ¿Qué tanto te motiva principalmente a viajar los siguientes aspectos?\n (Otro)", "7. Los medios donde buscas inspiración para elegir destinos en Hidalgo. (Otro)", "8. En cuanto a la confianza y uso de las tecnologías indica tu nivel en que estas de acuerdo con las siguientes frases: (Otro)", "9. ¿Qué factor influye más en tu decisión de seguir una recomendación turística? (Otro)", "12. ¿Qué tipo de información consideras más importante? (Otro)", "13. ¿Con qué frecuencia has enfrentado los siguientes problemas al viajar? (Otro)", "15. ¿Qué funciones consideras indispensables en una app de viajes? (Otro)", "17. En una frase, ¿qué esperas de una app turística ideal para viajar en Hidalgo?\n (Otro)"])

In [296]:
porcentajes = (df.isnull().sum()/len(df))*100

tabla_info = pd.DataFrame({

    "Data Type": df.dtypes,
    "No Nulos": df.notnull().sum(),
    "Valores Nulos" : df.isnull().sum(),
    "Porcentaje Nulos (%)": porcentajes.round(2),
})

tabla_info

,Data Type,No Nulos,Valores Nulos,Porcentaje Nulos (%)
1. ¿De dónde nos visitas?,object,806,1,0.12
1.1 ¿De qué municipio del estado de Hidalgo perteneces?,object,249,558,69.14
2. ¿En qué rango de edad te encuentras?,object,804,3,0.37
3. ¿Con qué género te identificas?\n,object,800,7,0.87
4. ¿Con qué frecuencia realizas viajes dentro de México?\n,object,798,9,1.12
5. ¿Cuántas veces ha visitado alguno de los destinos turísticos de Hidalgo en los últimos 24 meses?\n,object,803,4,0.50
6. ¿Qué tanto te motiva principalmente a viajar los siguientes aspectos?\n,object,806,1,0.12
7. Los medios donde buscas inspiración para elegir destinos en Hidalgo.,object,800,7,0.87
8. En cuanto a la confianza y uso de las tecnologías indica tu nivel en que estas de acuerdo con las siguientes frases:,object,795,12,1.49
9. ¿Qué factor influye más en tu decisión de seguir una recomendación turística?,object,805,2,0.25
10. En una escala del 1 al 5 donde 1 es Nada valioso y 5 es Muy valioso ¿Cómo sería para ti que una app turística te recomiende comercios y experiencias locales auténticas?\n,float64,802,5,0.62
"11. De una escala del 1 al 5 donde 1 es Totalmente en desacuerdo y 5 es Totalmente de acuerdo. Indica que tanto estás de acuerdo con la siguiente frase: ""Me sentiría más confiado/a usando una app turística si sé que las recomendaciones están validadas por personas locales o por una institución oficial.”\n",float64,801,6,0.74
12. ¿Qué tipo de información consideras más importante?,object,804,3,0.37
13. ¿Con qué frecuencia has enfrentado los siguientes problemas al viajar?,object,804,3,0.37
"14. En una escala del 1 al 5, donde 1 es nada probable y 5 muy probable. ¿Qué tan probable es que uses una app oficial del estado de Hidalgo para planear y vivir tus viajes?\n",object,799,8,0.99
15. ¿Qué funciones consideras indispensables en una app de viajes?,object,803,4,0.50
16. ¿Qué haría que dejaras de usar una app turística? (Selecciona 3 opciones),object,805,2,0.25
"17. En una frase, ¿qué esperas de una app turística ideal para viajar en Hidalgo?\n",object,718,89,11.03

In [297]:
df.shape

(807, 18)

Se realiza un tratamiento en las columnas *'1. ¿De dónde nos visitas?'* y *'1.1 ¿De qué municipio del Estado de Hidalgo perteneces?'* para estandarizar su formato y facilitar su lectura y presentación en Looker Studio.

In [298]:
df["1. ¿De dónde nos visitas?"] = df["1. ¿De dónde nos visitas?"].replace("Veracruz", "Veracruz de Ignacio de la Llave")

df["1. ¿De dónde nos visitas?"] = df["1. ¿De dónde nos visitas?"] + ", México" 

df["1.1 ¿De qué municipio del estado de Hidalgo perteneces?"] = df["1.1 ¿De qué municipio del estado de Hidalgo perteneces?"] + ", Hidalgo, México"

Del mismo modo, para la columna "14. En una escala del 1 al 5, donde 1 es nada probable y 5 muy probable. ¿Qué tan probable es que uses una app oficial del estado de Hidalgo para planear y vivir tus viajes?" muchas de las respuestas vienen en formato de texto tales como "Probable", "Muy poco probable" y otras si respetan la escala de intervalo 1-5, se transformará las respuestas de texto al valor correspondiente a la escala.

In [299]:
df.columns = df.columns.str.strip()

In [300]:
col = "14. En una escala del 1 al 5,  donde 1 es nada probable y 5 muy probable. ¿Qué tan probable es que uses una app oficial del estado de Hidalgo para planear y vivir tus viajes?"


mapping = {
    "Nada probable": 1,
    "Poco probable": 2,
    "Neutral": 3,
    "Probable": 4,
    "Muy probable": 5
}

df[col] = (
    df[col]
    .replace(mapping)
    .astype(float)         
)

La columna "7. Los medios donde buscas inspiración para elegir destinos en Hidalgo." tiene cadenas de texto diferentes que en esencia son la misma, se agruparán en Google, Redes Sociales, No busco inspiración y recomendaciones de amigos.

In [301]:
col = "7. Los medios donde buscas inspiración para elegir destinos en Hidalgo."

df[col] = df[col].astype(str).str.strip().str.lower()

df[col] = np.where(df[col].str.contains("google"), 
                   "Google",
            np.where(df[col].str.contains("redes"), 
                   "Redes Sociales",
            np.where(df[col].str.contains("no busco"), 
                   "No busco inspiración",
            np.where(df[col].str.contains("recomend"), 
                   "Recomendaciones de amigos / familia",
                   "Otro"))))

In [302]:
df.head()

,1. ¿De dónde nos visitas?,1.1 ¿De qué municipio del estado de Hidalgo perteneces?,2. ¿En qué rango de edad te encuentras?,3. ¿Con qué género te identificas?,4. ¿Con qué frecuencia realizas viajes dentro de México?,5. ¿Cuántas veces ha visitado alguno de los destinos turísticos de Hidalgo en los últimos 24 meses?,6. ¿Qué tanto te motiva principalmente a viajar los siguientes aspectos?,7. Los medios donde buscas inspiración para elegir destinos en Hidalgo.,8. En cuanto a la confianza y uso de las tecnologías indica tu nivel en que estas de acuerdo con las siguientes frases:,9. ¿Qué factor influye más en tu decisión de seguir una recomendación turística?,10. En una escala del 1 al 5 donde 1 es Nada valioso y 5 es Muy valioso ¿Cómo sería para ti que una app turística te recomiende comercios y experiencias locales auténticas?,"11. De una escala del 1 al 5 donde 1 es Totalmente en desacuerdo y 5 es Totalmente de acuerdo. Indica que tanto estás de acuerdo con la siguiente frase: ""Me sentiría más confiado/a usando una app turística si sé que las recomendaciones están validadas por personas locales o por una institución oficial.”",12. ¿Qué tipo de información consideras más importante?,13. ¿Con qué frecuencia has enfrentado los siguientes problemas al viajar?,"14. En una escala del 1 al 5, donde 1 es nada probable y 5 muy probable. ¿Qué tan probable es que uses una app oficial del estado de Hidalgo para planear y vivir tus viajes?",15. ¿Qué funciones consideras indispensables en una app de viajes?,16. ¿Qué haría que dejaras de usar una app turística? (Selecciona 3 opciones),"17. En una frase, ¿qué esperas de una app turística ideal para viajar en Hidalgo?"
0,"Campeche, México",NaN,50–59 años,Hombre,Esporádicamente,1 vez,Gastronomía,Recomendaciones de amigos / familia,Me generan seguridad para tomar decisiones,Opiniones de otros usuarios,5.0,4.0,Mapas y rutas,Falta de información en el momento exacto,5.0,Eventos y experiencias locales,Exceso de publicidad,Información que me ayude a decidir a donde ir
1,"Ciudad de México, México",NaN,18–29 años,Hombre,Varias veces al año,2 veces,Naturaleza,Otro,Me ayudan a ahorrar tiempo,Cercanía / ubicación,5.0,4.0,Eventos o actividades del día,Información desactualizada,5.0,Información verificada,Información falsa o incompleta,Información concreta
2,"Estado de México, México",NaN,18–29 años,Mujer,Varias veces al año,3 veces,Gastronomía,Recomendaciones de amigos / familia,La información suele ser clara y actualizada,Opiniones de otros usuarios,5.0,5.0,Eventos o actividades del día,Falta de información en el momento exacto,5.0,Comercios y servicios cercanos,"Información falsa o incompleta, Exceso de publ...",Auténtica
3,"Estado de México, México",NaN,30–39 años,Mujer,Esporádicamente,4 veces o más,Aventura,Redes Sociales,Me ayudan a ahorrar tiempo,Opiniones de otros usuarios,5.0,5.0,Otro: Todo,Falta de información en el momento exacto,5.0,Otro: Todas,"Información falsa o incompleta, Exceso de publ...",Todos los sitios turísticos y rutas y que no s...
4,"Ciudad de México, México",NaN,18–29 años,Mujer,Varias veces al año,2 veces,Naturaleza,Redes Sociales,Me ayudan a ahorrar tiempo,Opiniones de otros usuarios,5.0,5.0,Mapas y rutas,Falta de información en el momento exacto,5.0,Eventos y experiencias locales,Información falsa o incompleta,"Que sea funcional, rápida y actualizada"

In [303]:
df.to_csv('Datos_Finales_Turistas.csv', index=False, encoding='utf-8-sig')

<h4 style="color:#0F3D36; font-family:'Montserrat', sans-serif; font-size:20px; font-weight:600; margin-top:15px; margin-bottom:8px;">
Acercamiento Estadístico
</h4>

In [304]:
df.describe().round(2)

,10. En una escala del 1 al 5 donde 1 es Nada valioso y 5 es Muy valioso ¿Cómo sería para ti que una app turística te recomiende comercios y experiencias locales auténticas?,"11. De una escala del 1 al 5 donde 1 es Totalmente en desacuerdo y 5 es Totalmente de acuerdo. Indica que tanto estás de acuerdo con la siguiente frase: ""Me sentiría más confiado/a usando una app turística si sé que las recomendaciones están validadas por personas locales o por una institución oficial.”","14. En una escala del 1 al 5, donde 1 es nada probable y 5 muy probable. ¿Qué tan probable es que uses una app oficial del estado de Hidalgo para planear y vivir tus viajes?"
count,802.00,801.00,799.00
mean,4.36,4.31,3.99
std,0.90,0.93,1.13
min,1.00,1.00,1.00
25%,4.00,4.00,3.00
50%,5.00,5.00,4.00
75%,5.00,5.00,5.00
max,5.00,5.00,5.00

In [305]:
df.describe(include= "object")

,1. ¿De dónde nos visitas?,1.1 ¿De qué municipio del estado de Hidalgo perteneces?,2. ¿En qué rango de edad te encuentras?,3. ¿Con qué género te identificas?,4. ¿Con qué frecuencia realizas viajes dentro de México?,5. ¿Cuántas veces ha visitado alguno de los destinos turísticos de Hidalgo en los últimos 24 meses?,6. ¿Qué tanto te motiva principalmente a viajar los siguientes aspectos?,7. Los medios donde buscas inspiración para elegir destinos en Hidalgo.,8. En cuanto a la confianza y uso de las tecnologías indica tu nivel en que estas de acuerdo con las siguientes frases:,9. ¿Qué factor influye más en tu decisión de seguir una recomendación turística?,12. ¿Qué tipo de información consideras más importante?,13. ¿Con qué frecuencia has enfrentado los siguientes problemas al viajar?,15. ¿Qué funciones consideras indispensables en una app de viajes?,16. ¿Qué haría que dejaras de usar una app turística? (Selecciona 3 opciones),"17. En una frase, ¿qué esperas de una app turística ideal para viajar en Hidalgo?"
count,806,249,804,800,798,803,806,807,795,805,804,804,803,805,718
unique,27,43,5,3,4,4,10,5,6,9,9,11,10,77,526
top,"Hidalgo, México","Tula de Allende, Hidalgo, México",18–29 años,Mujer,Varias veces al año,4 veces o más,Descanso / relajación,Redes Sociales,Me ayudan a ahorrar tiempo,Opiniones de otros usuarios,Mapas y rutas,Información desactualizada,Recomendaciones locales confiables,Información falsa o incompleta,Confiable
freq,251,42,255,422,441,225,334,476,480,334,449,402,366,137,30

<h2 style="color:#9D2449; font-family:'Montserrat', sans-serif; font-size:28px; font-weight:700; margin-top:25px; margin-bottom:12px;">
Prestadores de Servicio
</h2>
<h4 style="color:#0F3D36; font-family:'Montserrat', sans-serif; font-size:20px; font-weight:600; margin-top:15px; margin-bottom:8px;">
Carga de Datos
</h4>

In [306]:
path_PST = "https://raw.githubusercontent.com/gonza98kg/Turistas/main/PST_data.csv"

df_PST = pd.read_csv(path_PST)

In [307]:
df_PST.head()

,Id,Tipo de Servicio que se ofrece:,Tipo de Servicio que se ofrece: (Otro),Años de operación:,¿Cómo te promocionas actualmente?,¿Cómo te promocionas actualmente? (Otro),¿Cómo describes la función de promoción actualmente?,¿Cómo te das a conocer actualmente?,¿Cómo te das a conocer actualmente? (Otro),De esos medios: Elige 3 que realmente te traen clientes.,...,¿Qué te haría confiar en una plataforma turística del gobierno del estado?,¿Qué tan valioso sería para ti aparecer en una app oficial que recomiende tu servicio a los visitantes?,"Si esa app existiera, ¿qué debería ofrecerte para que realmente la usaras?",¿Qué tan valioso consideras sería aparecer en una app turística oficial?,¿Qué funciones te resultarían más útiles?,En una escal del 1 al 5; donde 1 es nada y 5 totalmente. ¿Qué tanto confiaría en una plataforma que es oficial y gratuita?,"¿Qué tan dispuesto estarías a mantener tu información actualizada (por ejemplo de horarios, precios, fotos)?",¿Qué te motivaría a seguir usando la plataforma en el tiempo?,"Si pudieras pedirle algo a una plataforma turística para apoyar tu negocio, ¿qué sería?\n","En una frase, ¿qué esperas de una plataforma turística del estado?"
0,1,Artesanía,NaN,Más de 10 años,Recomendación directa,NaN,Las plataformas digitales me ayudan,De boca a boca,NaN,"Redes sociales, De boca a boca, Ferias",...,Que sea atractiva y segura,Muy valioso,"Seguridad, confianza, eficaz",Muy valioso,Recomendaciones a turistas,5.0,Muy dispuesto,La atracción del turista y crecimiento,"Atracción, seguridad, confianza",Que sea una herramienta de apoyo a los comerci...
1,2,Artesanía,NaN,Más de 10 años,Redes sociales,NaN,Las plataformas digitales me ayudan,Redes sociales,NaN,"Recomendaciones, Redes sociales, De boca a boca",...,"Que sea atractiva y tenga más publicidad, atra...",Muy valioso,"Seguridad, confianza, innovación",Muy valioso,Recomendaciones a turistas,5.0,Muy dispuesto,La publicidad a más turistas,Que sea seccionado qué tenga el apartado de du...,"Que sea confiable, innovador y crear seguridad..."
2,3,Artesanía,NaN,4–10 años,Recomendación directa,NaN,Me cuesta trabajo atraer visitantes,Recomendaciones,NaN,"Recomendaciones, Ferias, De boca a boca",...,"Que sea segura, confiable",Muy valioso,"Innovación, credibilidad",Muy valioso,Contacto directo con turistas,5.0,Muy dispuesto,Que sea real y crear seguridad,"Que muestre mis productos, que se reflejan mi...",Que sea una herramienta funcional y atractiva
3,4,Restaurante / café,NaN,Más de 10 años,Plataformas digitales,NaN,Las plataformas digitales me ayudan,Plataformas,NaN,"Redes sociales, De boca a boca, Recomendaciones",...,Que sea confiable,Muy valioso,Fácil de usar y que de buena promoción,Valioso,Recomendaciones a turistas,5.0,Dispuesto,La efectividad de la plataforma,Que sea confiable y efectiva,Que sea efectiva
4,5,Otro: Servicios,NaN,4–10 años,Recomendación directa,NaN,Las plataformas digitales me ayudan,Plataformas,NaN,"Redes sociales, Recomendaciones, De boca a boca",...,Si,Muy valioso,Ventas,Poco,Mayor visibilidad,5.0,Neutral,Mejorar ventas,Aumentar ventas,Promocionar el comercio local

In [308]:
df_PST.shape

(101, 29)

<h4 style="color:#0F3D36; font-family:'Montserrat', sans-serif; font-size:20px; font-weight:600; margin-top:15px; margin-bottom:8px;">
Diccionario
</h4>

| **Columna**                | **Tipo de dato**   | **Descripción**|
|----------------------------|--------------------|----------------|
| Tipo de Servicio que se ofrece: | Cadena (`string`)     | Servicio que ofrece el prestador |
| Años de operación: | Cadena (`string`)     | Periodo de funcionamiento del negocio/servicio |
| ¿Cómo te promocionas actualmente? | Cadena (`string`)     | Tipos de promoción del prestador actual |
| ¿Cómo describes la función de promoción actualmente? | Cadena (`string`)     | Percepción del prestador ante la forma de promoción actual |
| ¿Cómo te das a conocer actualmente? | Cadena (`string`)     | Medios por los que, directa o indirectamente, los prestadores dan a conocer sus negocios |
| De esos medios: Elige 3 que realmente te traen clientes. | Cadena (`string`)     | Medios del prestador para atraer clientes |
| ¿Usas alguna app o plataforma para promocionar tu servicio? ¿Cómo ha sido tu experiencia? | Cadena (`string`)     | Uso de herramientas digitales para la promoción del negocio |
| Cuéntame un poco sobre tu negocio o servicio. ¿Qué ofreces y a qué tipo de visitantes atiendes normalmente? | Cadena (`string`)     | Servicio que se ofrece y tipos de visitantes que se reciben |
| ¿Cómo es un día normal para ti cuando tienes visitantes o clientes? | Cadena (`string`)     | Percepcón y experiencia del prestador sobre un día de afluencia de clientela |
|¿Hay temporadas donde tienes muchos visitantes y otras donde casi no llegan? ¿Cómo te afecta eso? | Cadena (`string`)     | Mención de estacionalidad en las ventas de los prestadores |
| ¿Cuál dirías que es el principal problema que enfrentas para atraer más visitantes? | Cadena (`string`)     | Problemas por los que las personas objetivo no se sienten atraídas por el servicio |
| ¿Qué tan fácil o difícil te resulta usar herramientas digitales para promocionarte?  | Cadena (`string`)     | Dificultades de los prestadores para usar herramientas digitales como promoción |
| ¿Has tenido alguna mala experiencia con plataformas digitales o redes sociales? ¿Qué pasó? | Cadena (`string`)     | Existencia de dificultad para utilizar herramientas digitales por parte de los prestadores |
| Menciona ¿Cuál consideras sería la principal dificultad? | Cadena (`string`)     | Principales dificultades para usar herramientas digitales por parte de los prestadores |
| ¿Qué te haría confiar en una plataforma turística del gobierno del estado? | Cadena (`string`)     | Motivación para la confianza en una plataforma turística oficial |
| ¿Qué tan valioso sería para ti aparecer en una app oficial que recomiende tu servicio a los visitantes? | Cadena (`string`)     | Valoración de la participación del servicio del prestador en la app oficial |
| Si esa app existiera, ¿qué debería ofrecerte para que realmente la usaras? | Cadena (`string`)     | Requisitos o condiciones necesarias para la adopción de la app |
| ¿Qué tan valioso consideras sería aparecer en una app turística oficial? | Cadena (`string`)     | Valoración de la participación del prestador en la app oficial |
| ¿Qué funciones te resultarían más útiles? | Cadena (`string`)     | Expectativas del prestador sobre las funciones de la app oficial |
| En una escal del 1 al 5; donde 1 es nada y 5 totalmente. ¿Qué tanto confiaría en una plataforma que es oficial y gratuita? | Entero (`int`)     | Valoración de la confianza del prestador en una plataforma oficial |
| ¿Qué tan dispuesto estarías a mantener tu información actualizada (por ejemplo de horarios, precios, fotos)? | Cadena (`string`)     | Valoración de la disposición del prestador en actualizar constantemente información de su negocio |
| ¿Qué te motivaría a seguir usando la plataforma en el tiempo? | Cadena (`string`)     | Expectativas del prestador sobre la app oficial para la motivación de su uso |
| Si pudieras pedirle algo a una plataforma turística para apoyar tu negocio, ¿qué sería?  | Cadena (`string`)     | Necesidades estratégicas o expectativas de apoyo empresarial respecto a la app oficial |
| En una frase, ¿qué esperas de una plataforma turística del estado? | Cadena (`string`)     | Expectativas generales del prestador y percepción ideal sobre la plataforma oficial |

In [309]:
porcentajes = (df_PST.isnull().sum()/len(df))*100

tabla_info = pd.DataFrame({

    "Data Type": df_PST.dtypes,
    "No Nulos": df_PST.notnull().sum(),
    "Valores Nulos" : df_PST.isnull().sum(),
    "Porcentaje Nulos (%)": porcentajes.round(2),
})

tabla_info

,Data Type,No Nulos,Valores Nulos,Porcentaje Nulos (%)
Id,int64,101,0,0.00
Tipo de Servicio que se ofrece:,object,99,2,0.25
Tipo de Servicio que se ofrece: (Otro),float64,0,101,12.52
Años de operación:,object,99,2,0.25
¿Cómo te promocionas actualmente?,object,99,2,0.25
¿Cómo te promocionas actualmente? (Otro),float64,0,101,12.52
¿Cómo describes la función de promoción actualmente?,object,99,2,0.25
¿Cómo te das a conocer actualmente?,object,99,2,0.25
¿Cómo te das a conocer actualmente? (Otro),float64,0,101,12.52
De esos medios: Elige 3 que realmente te traen clientes.,object,99,2,0.25
De esos medios: Elige 3 que realmente te traen clientes. (Otro),float64,0,101,12.52
¿Usas alguna app o plataforma para promocionar tu servicio? ¿Cómo ha sido tu experiencia?,object,99,2,0.25
Cuéntame un poco sobre tu negocio o servicio. ¿Qué ofreces y a qué tipo de visitantes atiendes normalmente?,object,98,3,0.37
¿Cómo es un día normal para ti cuando tienes visitantes o clientes?,object,98,3,0.37
¿Hay temporadas donde tienes muchos visitantes y otras donde casi no llegan? ¿Cómo te afecta eso?,object,97,4,0.50
¿Cuál dirías que es el principal problema que enfrentas para atraer más visitantes?,object,99,2,0.25
¿Qué tan fácil o difícil te resulta usar herramientas digitales para promocionarte?\n,object,99,2,0.25
¿Has tenido alguna mala experiencia con plataformas digitales o redes sociales? ¿Qué pasó?,object,99,2,0.25
Menciona ¿Cuál consideras sería la principal dificultad?\n,object,99,2,0.25
¿Qué te haría confiar en una plataforma turística del gobierno del estado?,object,99,2,0.25
¿Qué tan valioso sería para ti aparecer en una app oficial que recomiende tu servicio a los visitantes?,object,99,2,0.25
"Si esa app existiera, ¿qué debería ofrecerte para que realmente la usaras?",object,99,2,0.25
¿Qué tan valioso consideras sería aparecer en una app turística oficial?,object,99,2,0.25
¿Qué funciones te resultarían más útiles?,object,99,2,0.25
En una escal del 1 al 5; donde 1 es nada y 5 totalmente. ¿Qué tanto confiaría en una plataforma que es oficial y gratuita?,float64,99,2,0.25
"¿Qué tan dispuesto estarías a mantener tu información actualizada (por ejemplo de horarios, precios, fotos)?",object,99,2,0.25
¿Qué te motivaría a seguir usando la plataforma en el tiempo?,object,98,3,0.37
"Si pudieras pedirle algo a una plataforma turística para apoyar tu negocio, ¿qué sería?\n",object,97,4,0.50
"En una frase, ¿qué esperas de una plataforma turística del estado?",object,91,10,1.24

<h4 style="color:#0F3D36; font-family:'Montserrat', sans-serif; font-size:20px; font-weight:600; margin-top:15px; margin-bottom:8px;">
Limpieza de la base de datos
</h4>

Se observa que algunas de las columnas presentan todos sus valores como nulos, por lo que serán eliminadas, así mismo, en la mayoría de columnas se presentan dos valores nulos, por lo que al revisarlos se observó que son filas vacias en su totalidad por lo que también serán eliminadas.

In [310]:
df_PST = df_PST.drop(columns = ["Id", 'Tipo de Servicio que se ofrece:  (Otro)', "¿Cómo te promocionas actualmente? (Otro)", "¿Cómo te das a conocer actualmente? (Otro)", "De esos medios: Elige 3 que realmente te traen clientes. (Otro)"])

In [311]:
df_PST.loc[df_PST["En una escal del 1 al 5; donde 1 es nada y 5 totalmente. ¿Qué tanto confiaría en una plataforma que es oficial y gratuita?"].isnull()]

,Tipo de Servicio que se ofrece:,Años de operación:,¿Cómo te promocionas actualmente?,¿Cómo describes la función de promoción actualmente?,¿Cómo te das a conocer actualmente?,De esos medios: Elige 3 que realmente te traen clientes.,¿Usas alguna app o plataforma para promocionar tu servicio? ¿Cómo ha sido tu experiencia?,Cuéntame un poco sobre tu negocio o servicio. ¿Qué ofreces y a qué tipo de visitantes atiendes normalmente?,¿Cómo es un día normal para ti cuando tienes visitantes o clientes?,¿Hay temporadas donde tienes muchos visitantes y otras donde casi no llegan? ¿Cómo te afecta eso?,...,¿Qué te haría confiar en una plataforma turística del gobierno del estado?,¿Qué tan valioso sería para ti aparecer en una app oficial que recomiende tu servicio a los visitantes?,"Si esa app existiera, ¿qué debería ofrecerte para que realmente la usaras?",¿Qué tan valioso consideras sería aparecer en una app turística oficial?,¿Qué funciones te resultarían más útiles?,En una escal del 1 al 5; donde 1 es nada y 5 totalmente. ¿Qué tanto confiaría en una plataforma que es oficial y gratuita?,"¿Qué tan dispuesto estarías a mantener tu información actualizada (por ejemplo de horarios, precios, fotos)?",¿Qué te motivaría a seguir usando la plataforma en el tiempo?,"Si pudieras pedirle algo a una plataforma turística para apoyar tu negocio, ¿qué sería?\n","En una frase, ¿qué esperas de una plataforma turística del estado?"
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [312]:
df_PST = df_PST.dropna(subset = "En una escal del 1 al 5; donde 1 es nada y 5 totalmente. ¿Qué tanto confiaría en una plataforma que es oficial y gratuita?")
df_PST.loc[df_PST["En una escal del 1 al 5; donde 1 es nada y 5 totalmente. ¿Qué tanto confiaría en una plataforma que es oficial y gratuita?"].isnull()]

Empty DataFrame
Columns: [Tipo de Servicio que se ofrece: , Años de operación:, ¿Cómo te promocionas actualmente?, ¿Cómo describes la función de promoción actualmente?, ¿Cómo te das a conocer actualmente?, De esos medios: Elige 3 que realmente te traen clientes., ¿Usas alguna app o plataforma para promocionar tu servicio? ¿Cómo ha sido tu experiencia?, Cuéntame un poco sobre tu negocio o servicio. ¿Qué ofreces y a qué tipo de visitantes atiendes normalmente?, ¿Cómo es un día normal para ti cuando tienes visitantes o clientes?, ¿Hay temporadas donde tienes muchos visitantes y otras donde casi no llegan? ¿Cómo te afecta eso?, ¿Cuál dirías que es el principal problema que enfrentas para atraer más visitantes?, ¿Qué tan fácil o difícil te resulta usar herramientas digitales para promocionarte?
, ¿Has tenido alguna mala experiencia con plataformas digitales o redes sociales? ¿Qué pasó?, Menciona ¿Cuál consideras sería la principal dificultad?
, ¿Qué te haría confiar en una plataforma turística del gobierno del estado?, ¿Qué tan valioso sería para ti aparecer en una app oficial que recomiende tu servicio a los visitantes?, Si esa app existiera, ¿qué debería ofrecerte para que realmente la usaras?, ¿Qué tan valioso consideras sería aparecer en una app turística oficial?, ¿Qué funciones te resultarían más útiles?, En una escal del 1 al 5; donde 1 es nada y 5 totalmente. ¿Qué tanto confiaría en una plataforma que es oficial y gratuita?, ¿Qué tan dispuesto estarías a mantener tu información actualizada (por ejemplo de horarios, precios, fotos)?, ¿Qué te motivaría a seguir usando la plataforma en el tiempo?, Si pudieras pedirle algo a una plataforma turística para apoyar tu negocio, ¿qué sería?
, En una frase, ¿qué esperas de una plataforma turística del estado?]
Index: []

[0 rows x 24 columns]

In [313]:
porcentajes = (df_PST.isnull().sum()/len(df))*100

tabla_info = pd.DataFrame({

    "Data Type": df_PST.dtypes,
    "No Nulos": df_PST.notnull().sum(),
    "Valores Nulos" : df_PST.isnull().sum(),
    "Porcentaje Nulos (%)": porcentajes.round(2),
})

tabla_info

,Data Type,No Nulos,Valores Nulos,Porcentaje Nulos (%)
Tipo de Servicio que se ofrece:,object,99,0,0.00
Años de operación:,object,99,0,0.00
¿Cómo te promocionas actualmente?,object,99,0,0.00
¿Cómo describes la función de promoción actualmente?,object,99,0,0.00
¿Cómo te das a conocer actualmente?,object,99,0,0.00
De esos medios: Elige 3 que realmente te traen clientes.,object,99,0,0.00
¿Usas alguna app o plataforma para promocionar tu servicio? ¿Cómo ha sido tu experiencia?,object,99,0,0.00
Cuéntame un poco sobre tu negocio o servicio. ¿Qué ofreces y a qué tipo de visitantes atiendes normalmente?,object,98,1,0.12
¿Cómo es un día normal para ti cuando tienes visitantes o clientes?,object,98,1,0.12
¿Hay temporadas donde tienes muchos visitantes y otras donde casi no llegan? ¿Cómo te afecta eso?,object,97,2,0.25
¿Cuál dirías que es el principal problema que enfrentas para atraer más visitantes?,object,99,0,0.00
¿Qué tan fácil o difícil te resulta usar herramientas digitales para promocionarte?\n,object,99,0,0.00
¿Has tenido alguna mala experiencia con plataformas digitales o redes sociales? ¿Qué pasó?,object,99,0,0.00
Menciona ¿Cuál consideras sería la principal dificultad?\n,object,99,0,0.00
¿Qué te haría confiar en una plataforma turística del gobierno del estado?,object,99,0,0.00
¿Qué tan valioso sería para ti aparecer en una app oficial que recomiende tu servicio a los visitantes?,object,99,0,0.00
"Si esa app existiera, ¿qué debería ofrecerte para que realmente la usaras?",object,99,0,0.00
¿Qué tan valioso consideras sería aparecer en una app turística oficial?,object,99,0,0.00
¿Qué funciones te resultarían más útiles?,object,99,0,0.00
En una escal del 1 al 5; donde 1 es nada y 5 totalmente. ¿Qué tanto confiaría en una plataforma que es oficial y gratuita?,float64,99,0,0.00
"¿Qué tan dispuesto estarías a mantener tu información actualizada (por ejemplo de horarios, precios, fotos)?",object,99,0,0.00
¿Qué te motivaría a seguir usando la plataforma en el tiempo?,object,98,1,0.12
"Si pudieras pedirle algo a una plataforma turística para apoyar tu negocio, ¿qué sería?\n",object,97,2,0.25
"En una frase, ¿qué esperas de una plataforma turística del estado?",object,91,8,0.99

Se ha realizado la limpieza en la base de datos; para esta primer etapa en la presentación de datos no se imputaran ni se empleará ningún otro método de tratamiento de los valores nulos; este tratamiento será realizado posteriormente para el análisis de los datos. El porcentaje de valores nulos es muy bajo, apenas llegando al $1\%$ en algunas columnas.

Ahora se hará un tratamiento en los datos para algunas columnas a fin de homogeneizar las respuestas en categorías para una mejor presentación en la base de datos.

En la columna $"\texttt{Tipo de Servicio que se ofrece}"$ se encuentra que las respuestas pueden agruparse por categorías, por ejemplo, se tiene la categoría "Artesanías" y muchas de las respuestas están como "Otro: Artesanía"

In [314]:
conteo_servicios = df_PST['Tipo de Servicio que se ofrece: '].value_counts().sort_index()
print(conteo_servicios)

Tipo de Servicio que se ofrece:
Artesanía                                              42
Guía / experiencia                                      3
Hospedaje                                               7
Otro: Abarrotes                                         1
Otro: Artesania                                         1
Otro: Artesanias                                        1
Otro: Artesanías y papelería                            1
Otro: Botanas                                           1
Otro: Café y helados                                    1
Otro: Dulce artesanal                                   1
Otro: Dulces                                            1
Otro: Frutas y verduras                                 1
Otro: Medicina                                          1
Otro: Miscelanea                                        1
Otro: Papeleria                                         1
Otro: Productos de limpieza                             1
Otro: Regalos farmacia tienda                           1
Otro: Servicio  de internet                             1
Otro: Servicio de hospedaje y recorridos turísticos     1
Otro: Servicios                                         1
Otro: Tiend                                             1
Otro: Tortillas y pollos                                1
Otro: Transporte                                        1
Otro: Turismo de salud                                  1
Otro: Venta de ropa                                     1
Otro: Ventas pollo                                      1
Restaurante / café                                     24
Name: count, dtype: int64

A partir de la lista anterior se crea una función para clasificar servicios en distintas categorías como "Hospedaje", "Alimentos y Bebidas", "Artesanías y Comercio", "Actividades y Experiencias", "Transporte"

In [315]:
def clasificar_servicio(texto):
    if pd.isna(texto):
        return 'Sin Dato'
    texto = str(texto).lower()
    
    # HOSPEDAJE
    if any(x in texto for x in ['hotel', 'cabaña', 'posada', 'hospedaje', 'airbnb', 'hostal', 'glamping', 'habitacion', 'habitación']):
        return 'Hospedaje'
    
    # ALIMENTOS Y BEBIDAS
    elif any(x in texto for x in ['restaurante', 'comida', 'alimento', 'cocina', 'bar', 'café', 'cafe', 
                                  'pulque', 'pastes', 'gastronom', 'panader', 
                                  'pollo', 'tortilla', 'botana', 'helado', 'dulce', 'fruta', 'verdura']):
        return 'Alimentos y Bebidas'
    
    # 3 EXPERIENCIAS
    elif any(x in texto for x in ['guía', 'guia', 'tour', 'recorrido', 'balneario', 'temazcal', 
                                  'museo', 'parque', 'senderismo', 'experiencia', 'taller', 'zona arque', 'salud']):
        return 'Actividades y Experiencias'
    
    # 4. ARTESANÍAS Y COMERCIO
    elif any(x in texto for x in ['artesan', 'souvenir', 'regalo', 'ixtle', 'bordado', 'tienda', 
                                  'abarrotes', 'miscelanea', 'papeleria', 'farmacia', 'medicina', 
                                  'limpieza', 'ropa', 'tiend', 'internet']):
        return 'Artesanías y Comercio'
    
    # 5. TRANSPORTE
    elif any(x in texto for x in ['transporte', 'taxi', 'traslado', 'renta']):
        return 'Transporte'
        
    else:
        return 'Otros Servicios'

df_PST['Tipo de Servicio que se ofrece: '] = df_PST['Tipo de Servicio que se ofrece: '].apply(clasificar_servicio)
print(df_PST['Tipo de Servicio que se ofrece: '].value_counts())

Tipo de Servicio que se ofrece:
Artesanías y Comercio         53
Alimentos y Bebidas           32
Hospedaje                      8
Actividades y Experiencias     4
Otros Servicios                1
Transporte                     1
Name: count, dtype: int64

En la columna $\texttt{¿Cómo te das a conocer actualmente?}$ algunas de las respuestas que entran en la categoría de "Redes sociales" se registraron como "Otro" por lo que se homogeneizará en este caso.

In [316]:
columna = '¿Cómo te das a conocer actualmente?'

reemplazos = {
    'Otro: Redes sociales y personalmente': 'Redes sociales',
    'Otro: Google maps': 'Redes sociales'
}

df_PST[columna] = df_PST[columna].replace(reemplazos)

print(df_PST[columna].value_counts())

¿Cómo te das a conocer actualmente?
De boca a boca                                28
Recomendaciones                               25
Redes sociales                                23
Plataformas                                   11
Ferias                                        10
Otro: Con publicidad que toman en el local     1
Otro: Por visitas de turistas                  1
Name: count, dtype: int64

Para evaluar la efectividad de los canales de adquisición en la columna $\texttt{"De esos medios: Elige 3 que realmente te traen clientes"}$, se realizará un desglose de frecuencias de respuesta múltiple sobre la variable 'Medios que traen clientes'. Dado que los prestadores de servicios podían seleccionar varias opciones simultáneamente (ej. 'Redes sociales, Recomendaciones'), se separarán estos registros en valores individuales para cuantificar la incidencia real de cada canal. Este procedimiento permitirá jerarquizar los medios de promoción por su efectividad aislada, revelando si la tracción turística en Hidalgo depende mayoritariamente de esfuerzos digitales o de la reputación tradicional (boca a boca).

In [317]:
columna_medios = 'De esos medios: Elige 3 que realmente te traen clientes.'
medios_sucios = df_PST[columna_medios].dropna().str.split(', ', expand=True).stack()

correcciones = {
    '["Redes sociales"': 'Redes sociales',
    '"Ferias"': 'Ferias',
    '"other"] (otro: Google maps y también instagram)': 'Redes sociales',
    '"other"] (otro: Publicidad)': 'Publicidad Tradicional'
}
conteo_final = medios_sucios.replace(correcciones).value_counts()


df_tabla_final = conteo_final.reset_index()
df_tabla_final.columns = ['Medio de Promoción', 'Frecuencia']


print(df_tabla_final)

       Medio de Promoción  Frecuencia
0          De boca a boca          78
1         Recomendaciones          71
2          Redes sociales          57
3                  Ferias          32
4             Plataformas          22
5  Publicidad Tradicional           1

Con el objetivo de facilitar la lectura e interpretación de los gráficos en el tablero de control, se realizó una recodificación de la variable binaria sobre el uso de aplicaciones digitales. Los valores lógicos originales (True/False) fueron sustituidos por etiquetas categóricas explícitas ('Sí' y 'No'), eliminando la necesidad de traducción técnica por parte de la audiencia final.

In [318]:

columna_apps = '¿Usas alguna app o plataforma para promocionar tu servicio? ¿Cómo ha sido tu experiencia?'

cambios = {
    'FALSO': 'No', 
    'VERDADERO': 'Sí',
}
df_PST.loc[:, columna_apps] = df_PST[columna_apps].replace(cambios)

print(df_PST[columna_apps].value_counts())

¿Usas alguna app o plataforma para promocionar tu servicio? ¿Cómo ha sido tu experiencia?
No    64
Sí    35
Name: count, dtype: int64

Dada la naturaleza cualitativa de la variable sobre estacionalidad, se aplicó un proceso de categorización semántica para estructurar las respuestas abiertas. Se generó una nueva variable analítica ('Estacionalidad_Categoria') que clasifica los comentarios en dimensiones medibles: Dependencia de Calendario (vacaciones/festivos) y Vulnerabilidad Económica (impacto en ingresos). Esta transformación permite cuantificar no solo los periodos de baja afluencia, sino la severidad con la que los prestadores de servicios perciben la inestabilidad de la demanda.

In [319]:
col_original = '¿Hay temporadas donde tienes muchos visitantes y otras donde casi no llegan? ¿Cómo te afecta eso?'

def clasificar_estacionalidad(texto):
    if pd.isna(texto): return 'Sin Dato'
    t = str(texto).lower()
    
    if any(x in t for x in ['vacacion', 'vacion', 'semana', 'marzo', 'diciembre', 'navidad', 'puente', 'feria']):
        return 'Temporada Vacacional'
    elif any(x in t for x in ['fin de semana', 'fines', 'sabado', 'domingo']):
        return 'Fines de Semana'
    elif any(x in t for x in ['econom', 'venta', 'ingreso', 'dinero', 'baja', 'afecta', 'poco', 'gente']):
        return 'Impacto Económico / Baja Afluencia'
    elif 'no' in t and len(t) < 15: # Respuestas cortas negativas
         return 'Flujo Constante / No afecta'
    else:
        return 'Variable / Otro'

valores_nuevos = df_PST[col_original].apply(clasificar_estacionalidad)

indice = df_PST.columns.get_loc(col_original)

col_nueva = 'Estacionalidad_Categoria'
if col_nueva in df_PST.columns:
    df_PST[col_nueva] = valores_nuevos 
else:
    df_PST.insert(loc=indice + 1, column=col_nueva, value=valores_nuevos)

print(df_PST[col_nueva].value_counts())

Estacionalidad_Categoria
Impacto Económico / Baja Afluencia    44
Temporada Vacacional                  34
Variable / Otro                       18
Sin Dato                               2
Fines de Semana                        1
Name: count, dtype: int64

Para cuantificar las barreras de crecimiento, se procesó la variable abierta sobre problemáticas principales mediante un análisis de frecuencia de palabras clave. Las respuestas textuales originales fueron sobrescritas y estandarizadas en cuatro categorías macro: Deficiencias de Infraestructura/Acceso (carreteras, señalética), Falta de Visibilidad (promoción, publicidad), Limitaciones Económicas y Otros Factores. Esta recodificación permite identificar claramente el 'cuello de botella' principal que frena la llegada de turistas.

In [320]:
def clasificar_problema(texto):
    if pd.isna(texto): return 'Sin Dato'
    t = str(texto).lower()
    
    if any(x in t for x in ['carretera', 'camino', 'transporte', 'vialidad', 'señal', 'calle', 'acceso', 'bache', 'obra', 'ubicacion', 'llegar']):
        return 'Infraestructura y Acceso'
    elif any(x in t for x in ['publicidad', 'promocion', 'difusion', 'conocen', 'visibilidad', 'redes', 'marketing', 'internet', 'tecnolog']):
        return 'Falta de Publicidad / Visibilidad'
    elif any(x in t for x in ['dinero', 'recurso', 'econom', 'costo', 'presupuesto', 'inver', 'caro']):
        return 'Falta de Recursos / Inversión'
    elif any(x in t for x in ['ningun', 'nada', 'todo bien']):
        return 'Ninguno'
    else:
        return 'Otro Factor / No Especifica'

col_problema = '¿Cuál dirías que es el principal problema que enfrentas para atraer más visitantes?'

df_PST[col_problema] = df_PST[col_problema].apply(clasificar_problema)

print(df_PST[col_problema].value_counts())

¿Cuál dirías que es el principal problema que enfrentas para atraer más visitantes?
Otro Factor / No Especifica          45
Infraestructura y Acceso             41
Falta de Publicidad / Visibilidad     7
Falta de Recursos / Inversión         4
Ninguno                               2
Name: count, dtype: int64

Se evaluó la barrera de entrada tecnológica mediante la recodificación de la variable de percepción de uso digital. Las respuestas abiertas, que variaban desde negaciones simples hasta explicaciones complejas, fueron homologadas en una escala de tres niveles: 'Fácil / Accesible', 'Regular / Neutro' y 'Difícil / Complicado'. Esta estandarización permite cuantificar el porcentaje de la población objetivo que requiere capacitación técnica prioritaria frente a aquellos que ya dominan las herramientas básicas.

In [321]:
def clasificar_facilidad(texto):
    if pd.isna(texto): return 'Sin Dato'
    t = str(texto).lower()
    
    # DIFÍCIL
    if any(x in t for x in ['dificil', 'difícil', 'complic', 'cuesta', 'batall', 'no le entiendo', 'no se usar', 'no entiendo', 'mucho']):
        # "Mucho" usualmente responde a "¿Qué tan difícil?" -> "Mucho"
        return 'Difícil / Complicado'

    # FÁCIL
    elif any(x in t for x in ['facil', 'fácil', 'sencill', 'no es complic', 'no es dific', 'no me es dif', 'ayuda', 'aprender']):
        return 'Fácil / Accesible'
        
    # REGULAR
    elif any(x in t for x in ['mas o menos', 'más o menos', 'regular', 'poco', 'veces', 'depend']):
        return 'Regular / Neutro'
    
    # Ruido
    else:
        return 'Difícil / Complicado'

col_facilidad = '¿Qué tan fácil o difícil te resulta usar herramientas digitales para promocionarte?\n'

df_PST[col_facilidad] = df_PST[col_facilidad].apply(clasificar_facilidad)
print(df_PST[col_facilidad].value_counts())

¿Qué tan fácil o difícil te resulta usar herramientas digitales para promocionarte?\n
Difícil / Complicado    70
Fácil / Accesible       26
Regular / Neutro         3
Name: count, dtype: int64

Para dimensionar las barreras de confianza en el entorno digital, se realizó una clasificación temática de riesgos basada en las experiencias narrativas de los encuestados. La variable original fue estandarizada en tres categorías críticas: Vulnerabilidad Financiera (fraudes y estafas), Gestión de Reputación (malas reseñas/crisis) y Ausencia de Incidencias. Esta transformación permite cuantificar no solo la frecuencia de uso, sino la severidad de los obstáculos reales que frenan la adopción tecnológica en la región.

In [322]:
def clasificar_miedo(texto):
    if pd.isna(texto): return 'Sin Dato'
    t = str(texto).lower()
    
    # 1. FRAUDES
    if any(x in t for x in ['fraude', 'estafa', 'dinero', 'deposito', 'falso', 'robo', 'perfil']):
        return 'Fraudes o Estafas'
        
    # 2. REPUTACIÓN
    elif any(x in t for x in ['reseña', 'comentario', 'disgusto', 'vistas', 'bajan', 'mala']):
        return 'Malas Reseñas / Gestión de Reputación'
    
    # 3. SIN PROBLEMAS
    elif any(x in t for x in ['no', 'ningun', 'nunca', 'todo bien', 'buena']):
        return 'Sin Malas Experiencias'
        
    else:

        return 'Otras Incidencias Técnicas'

col_miedo = '¿Has tenido alguna mala experiencia con plataformas digitales o redes sociales? ¿Qué pasó?'

df_PST[col_miedo] = df_PST[col_miedo].apply(clasificar_miedo)

print(df_PST[col_miedo].value_counts())

¿Has tenido alguna mala experiencia con plataformas digitales o redes sociales? ¿Qué pasó?
Sin Malas Experiencias                   84
Fraudes o Estafas                         8
Malas Reseñas / Gestión de Reputación     6
Otras Incidencias Técnicas                1
Name: count, dtype: int64

El análisis de los motivadores de retención revela un enfoque pragmático por parte de los prestadores de servicios turísticos. La continuidad en el uso de la plataforma está condicionada principalmente por la obtención de Resultados Tangibles (aumento directo en ventas y afluencia de visitantes), seguido por la necesidad de Visibilidad y Promoción. Factores como la Facilidad de Uso y el Aprendizaje aparecen como habilitadores secundarios, lo que confirma que la adopción tecnológica en este sector depende menos de la innovación por sí misma y más del retorno de inversión visible que la herramienta pueda generar.

In [323]:
def clasificar_motivacion_final(texto):
    if pd.isna(texto): return 'Sin Dato'
    t = str(texto).lower()
    
    # 1. RESULTADOS ECONÓMICOS
    if any(x in t for x in ['venta', 'ingreso', 'ganancia', 'cliente', 'turista', 'visitante', 'econom', 'resultado', 'beneficio', 'negocio', 'aument']):
        return 'Resultados Tangibles (Ventas/Ingresos)'
        
    # 2. VISIBILIDAD Y ALCANCE
    elif any(x in t for x in ['promocion', 'publicidad', 'conocer', 'visibil', 'difusi', 'vista', 'imagen', 'gente', 'publico', 'atraer']):
        return 'Mayor Visibilidad y Promoción'
        
    # 3. FACILIDAD Y FUNCIONALIDAD
    elif any(x in t for x in ['facil', 'sencill', 'rapid', 'sirv', 'funcion', 'util', 'accesib', 'herramienta', 'manejo']):
        return 'Facilidad de Uso / Utilidad'

    # 4. APRENDIZAJE
    elif any(x in t for x in ['aprender', 'actualiz', 'capacit', 'mejorar', 'superar', 'conocimiento']):
        return 'Aprendizaje y Capacitación'

    # 5. CONFIANZA
    elif any(x in t for x in ['confianza', 'seguridad', 'apoyo', 'oficial', 'gobierno', 'verdad']):
        return 'Confianza y Respaldo Institucional'
        
    else:
        return 'Otros / Indeciso'

col_motiva = '¿Qué te motivaría a seguir usando la plataforma en el tiempo?'
df_PST[col_motiva] = df_PST[col_motiva].apply(clasificar_motivacion_final)

print(df_PST[col_motiva].value_counts())

¿Qué te motivaría a seguir usando la plataforma en el tiempo?
Resultados Tangibles (Ventas/Ingresos)    63
Otros / Indeciso                          22
Aprendizaje y Capacitación                 5
Confianza y Respaldo Institucional         4
Mayor Visibilidad y Promoción              4
Sin Dato                                   1
Name: count, dtype: int64

In [324]:
print(df_PST.columns.tolist())

['Tipo de Servicio que se ofrece: ', 'Años de operación:', '¿Cómo te promocionas actualmente?', '¿Cómo describes la función de promoción actualmente?', '¿Cómo te das a conocer actualmente?', 'De esos medios: Elige 3 que realmente te traen clientes.', '¿Usas alguna app o plataforma para promocionar tu servicio? ¿Cómo ha sido tu experiencia?', 'Cuéntame un poco sobre tu negocio o servicio. ¿Qué ofreces y a qué tipo de visitantes atiendes normalmente?', '¿Cómo es un día normal para ti cuando tienes visitantes o clientes?', '¿Hay temporadas donde tienes muchos visitantes y otras donde casi no llegan? ¿Cómo te afecta eso?', 'Estacionalidad_Categoria', '¿Cuál dirías que es el principal problema que enfrentas para atraer más visitantes?', '¿Qué tan fácil o difícil te resulta usar herramientas digitales para promocionarte?\n', '¿Has tenido alguna mala experiencia con plataformas digitales o redes sociales? ¿Qué pasó?', 'Menciona ¿Cuál consideras sería la principal dificultad?\n', '¿Qué te haría confiar en una plataforma turística del gobierno del estado?', '¿Qué tan valioso sería para ti aparecer en una app oficial que recomiende tu servicio a los visitantes?', 'Si esa app existiera, ¿qué debería ofrecerte para que realmente la usaras?', '¿Qué tan valioso consideras sería aparecer en una app turística oficial?', '¿Qué funciones te resultarían más útiles?', 'En una escal del 1 al 5; donde 1 es nada y 5 totalmente. ¿Qué tanto confiaría en una plataforma que es oficial y gratuita?', '¿Qué tan dispuesto estarías a mantener tu información actualizada (por ejemplo de horarios, precios, fotos)?', '¿Qué te motivaría a seguir usando la plataforma en el tiempo?', 'Si pudieras pedirle algo a una plataforma turística para apoyar tu negocio, ¿qué sería?\n', 'En una frase, ¿qué esperas de una plataforma turística del estado?']

In [325]:
conteo_servicios = df_PST['En una frase, ¿qué esperas de una plataforma turística del estado?'].value_counts().sort_index()
print(conteo_servicios)

En una frase, ¿qué esperas de una plataforma turística del estado?
300%incremento de ventas.                                         1
Agilidad, y buena imagen                                          1
Apoyo                                                             1
Atracción de clientes                                             1
Aumentar  ventas                                                  2
                                                                 ..
Rapidez y fácil entendimiento                                     1
Sea cierta, que sea atractiva, que motive a visitar el lugar.     1
Seguridad                                                         1
Seguridad y confianza                                             1
Seguridad y promoción de las artesanías del estado de hidalgo     1
Name: count, Length: 82, dtype: int64

<h4 style="color:#0F3D36; font-family:'Montserrat', sans-serif; font-size:20px; font-weight:600; margin-top:15px; margin-bottom:8px;">
Acercamiento Estadístico
</h4>

In [326]:
df_PST.describe().round(2)

       En una escal del 1 al 5; donde 1 es nada y 5 totalmente. ¿Qué tanto confiaría en una plataforma que es oficial y gratuita?
count                                               99.0
mean                                                 4.3
std                                                  0.9
min                                                  1.0
25%                                                  4.0
50%                                                  5.0
75%                                                  5.0
max                                                  5.0

In [327]:
df_PST.describe(include="object")

,Tipo de Servicio que se ofrece:,Años de operación:,¿Cómo te promocionas actualmente?,¿Cómo describes la función de promoción actualmente?,¿Cómo te das a conocer actualmente?,De esos medios: Elige 3 que realmente te traen clientes.,¿Usas alguna app o plataforma para promocionar tu servicio? ¿Cómo ha sido tu experiencia?,Cuéntame un poco sobre tu negocio o servicio. ¿Qué ofreces y a qué tipo de visitantes atiendes normalmente?,¿Cómo es un día normal para ti cuando tienes visitantes o clientes?,¿Hay temporadas donde tienes muchos visitantes y otras donde casi no llegan? ¿Cómo te afecta eso?,...,Menciona ¿Cuál consideras sería la principal dificultad?\n,¿Qué te haría confiar en una plataforma turística del gobierno del estado?,¿Qué tan valioso sería para ti aparecer en una app oficial que recomiende tu servicio a los visitantes?,"Si esa app existiera, ¿qué debería ofrecerte para que realmente la usaras?",¿Qué tan valioso consideras sería aparecer en una app turística oficial?,¿Qué funciones te resultarían más útiles?,"¿Qué tan dispuesto estarías a mantener tu información actualizada (por ejemplo de horarios, precios, fotos)?",¿Qué te motivaría a seguir usando la plataforma en el tiempo?,"Si pudieras pedirle algo a una plataforma turística para apoyar tu negocio, ¿qué sería?\n","En una frase, ¿qué esperas de una plataforma turística del estado?"
count,99,99,99,99,99,99,99,98,98,97,...,99,99,99,99,99,99,99,99,97,91
unique,6,4,8,4,7,35,2,89,86,86,...,5,87,5,90,5,5,5,6,83,82
top,Artesanías y Comercio,Más de 10 años,No me promociono,Las plataformas digitales me ayudan,De boca a boca,"Redes sociales, Recomendaciones, De boca a boca",No,Turistas,Normal,Si,...,Falta de conocimientos digitales,Seguridad,Muy valioso,Seguridad,Valioso,Recomendaciones a turistas,Muy dispuesto,Resultados Tangibles (Ventas/Ingresos),Difusión,Confiable
freq,53,53,34,35,28,14,64,6,4,5,...,39,4,44,4,43,38,41,63,5,6

In [328]:
df_PST.to_csv('Datos_Finales_PST.csv', index=False, encoding='utf-8-sig')

<h4 style="color:#0F3D36; font-family:'Montserrat', sans-serif; font-size:20px; font-weight:600; margin-top:15px; margin-bottom:8px;">
Conclusiones del Proceso de Preparación de Datos
</h4>

El proceso de limpieza y estandarización derivó en dos bases de datos listas para su análisis y visualización:

- **`Datos_Finales_Turistas.csv`** — 807 registros con limpieza menor: eliminación de columnas nulas redundantes, estandarización geográfica y recodificación de respuestas mixtas (texto/escala) en la variable de intención de uso de la app.
- **`Datos_Finales_PST.csv`** — ~100 registros con tratamiento más profundo: agrupación semántica de respuestas abiertas en categorías analíticas para tipo de servicio, canales de promoción, estacionalidad, barreras de crecimiento, percepción tecnológica y motivadores de retención.

El hallazgo transversal más relevante es que **la adopción tecnológica en ambas poblaciones está condicionada por resultados tangibles**: los turistas esperan personalización y facilidad de uso, mientras que los PST priorizan el incremento directo en ventas y visibilidad. Ambas perspectivas orientan los **MVP** de la aplicación de turismo estatal.